### ISSUE TITLE
ImportError: No module named 'cairo' after "successful" install? 

### ISSUE THREAD

**Issue by nickeubank** [conda-forge/cairo-feedstock#24]
Install into clean environment:

    ➜  ~ conda create -n cairo_test
    Fetching package metadata ...........
    Solving package specifications: 
    Package plan for installation in environment /Users/Nick/anaconda/envs/cairo_test:

    Proceed ([y]/n)? y

    #
    # To activate this environment, use:
    # > source activate cairo_test
    #
    # To deactivate this environment, use:
    # > source deactivate cairo_test
    #

    ➜  ~ source activate cairo_test
    (cairo_test) ➜  ~ conda install cairo -c conda-forge
    Fetching package metadata ...........
    Solving package specifications: .

    Package plan for installation in environment /Users/Nick/anaconda/envs/cairo_test:

    The following NEW packages will be INSTALLED:

        cairo:      1.14.6-4 conda-forge
        fontconfig: 2.12.1-4 conda-forge
        freetype:   2.7-1    conda-forge
        gettext:    0.19.7-1 conda-forge
        glib:       2.51.4-0 conda-forge
        icu:        58.1-1   conda-forge
        libffi:     3.2.1-3  conda-forge
        libiconv:   1.14-4   conda-forge
        libpng:     1.6.28-0 conda-forge
        libxml2:    2.9.4-4  conda-forge
        pcre:       8.39-0   conda-forge
        pixman:     0.34.0-0 conda-forge
        xz:         5.2.2-0  conda-forge
        zlib:       1.2.11-0 conda-forge

    Proceed ([y]/n)? y

    (cairo_test) ➜  ~ conda list
    # packages in environment at /Users/Nick/anaconda/envs/cairo_test:
    #
    cairo                     1.14.6                        4    conda-forge
    fontconfig                2.12.1                        4    conda-forge
    freetype                  2.7                           1    conda-forge
    gettext                   0.19.7                        1    conda-forge
    glib                      2.51.4                        0    conda-forge
    icu                       58.1                          1    conda-forge
    libffi                    3.2.1                         3    conda-forge
    libiconv                  1.14                          4    conda-forge
    libpng                    1.6.28                        0    conda-forge
    libxml2                   2.9.4                         4    conda-forge
    pcre                      8.39                          0    conda-forge
    pixman                    0.34.0                        0    conda-forge
    xz                        5.2.2                         0    conda-forge
    zlib                      1.2.11                        0    conda-forge

Failed import: 

    (cairo_test) ➜  ~ python
    Python 3.5.3 | packaged by conda-forge | (default, Feb 10 2017, 07:09:50) 
    [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import cairo
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named 'cairo'
    >>> 

Conda info: 
    
        
        (cairo_test) ➜  ~ conda info
    Current conda install:

                   platform : osx-64
              conda version : 4.3.16
           conda is private : False
          conda-env version : 4.3.16
        conda-build version : not installed
             python version : 3.5.3.final.0
           requests version : 2.13.0
           root environment : /Users/Nick/anaconda  (writable)
        default environment : /Users/Nick/anaconda/envs/cairo_test
           envs directories : /Users/Nick/anaconda/envs
                              /Users/Nick/.conda/envs
              package cache : /Users/Nick/anaconda/pkgs
                              /Users/Nick/.conda/pkgs
               channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://repo.continuum.io/pkgs/free/osx-64
                              https://repo.continuum.io/pkgs/free/noarch
                              https://repo.continuum.io/pkgs/r/osx-64
                              https://repo.continuum.io/pkgs/r/noarch
                              https://repo.continuum.io/pkgs/pro/osx-64
                              https://repo.continuum.io/pkgs/pro/noarch
                config file : /Users/Nick/.condarc
               offline mode : False
                 user-agent : conda/4.3.16 requests/2.13.0 CPython/3.5.3 Darwin/16.5.0 OSX/10.12.4
                    UID:GID : 501:20

**Comment by pkgw** [comment]
The `cairo` package just provides the Cairo native code library. You should install the `cairocffi` library to gain access to Cairo in Python.

(There is also a `pycairo` package, but it is extremely outdated. The `cairocffi` package is completely compatible with it, so you can use:

```
import cairocffi as cairo
```

And existing code should still work.)

**Comment by nickeubank** [comment]
@pkgw Thanks! That did it! :)

**Comment by pkgw** [comment]
Hah, although actually, literally today, someone took charge and released a new version of `pycairo`, after the project had been stagnant for literally years. I may submit an updated `pycairo` package since only that module is currently compatible with the GLib GObject introspection system.

**Comment by jakirkham** [comment]
Thanks for helping clear this up, @pkgw.

Naming issues like these between libraries and binding packages come up often enough (e.g. `cairo`, `graphviz`, `libtiff`, etc.) that I wonder if we shouldn't have add something to the docs (maybe `conda-forge_gotchas` ) to clarify these sorts of things. Additionally this we could always add a recipe level README. Another consideration would be adding a post-link script to these packages that prints something like, "Congratulations! You have just installed the `cairo` library. If you are looking for Python bindings to this library, please install `pycairo`. Thanks!". That way users would be aware immediately after they install one of these libraries that they need to go elsewhere to get `python` bindings. Maybe doing these sorts of things will help avoid confusion on these sort of points. Something to think about.

**Comment by pkgw** [comment]
Yeah, I bet things like this come up a lot. I'm really not a fan of package installs that produce output aimed at users ... but no one reads documentation, either.

RPM has a concept where packages can "provide" virtual resources, so if you know that you want to  install whatever package provides the TeX file `article.sty`, you can ask to install `tex(article.sty)` and it will look up the right package for you. For Conda the analogue would be that people are generally asking to install `python_module(cairo)`, not “the package named cairo”. Obviously that’s not what you'd want the user experience to be like, though! Maybe the path forward is to have a mode (the default?) where `conda install` treats its arguments as specifying a set of Python modules that are to be made available, rather than a set of particular package names to install.

**Comment by joanna350** [comment]
Hi... it still doesn't work for me..any other solution?

**Comment by pkgw** [comment]
@joanna350 If you have installed the `pycairo` package and are still unable to `import cairo` in Python, please file a bug [here, on the pycairo feedstock](https://github.com/conda-forge/pycairo-feedstock/issues/new), including pasting the output that you get from running the commands `conda info` and `conda list`. Thanks!

**Comment by joanna350** [comment]
I have cairo using 'conda install -c conda-forge cairo'. I will do as you say.. I can see the folder under //anaconda/pkgs/ and the directory is in fact returned from 'sys.path'. I have no idea what is wrong ㅜㅜㅜㅜㅜㅜㅜㅜㅜ

**Comment by Tarang74** [comment]
> The `cairo` package just provides the Cairo native code library. You should install the `pycairo` package to gain access to Cairo in Python.
> 
> **edit:** this used to suggest `cairocffi`, but `pycairo` is back to being the preferred package to use. Old text reserved for posterity:
> 
> > (There is also a `pycairo` package, but it is extremely outdated. The `cairocffi` package is completely compatible with it, so you can use:
> > ```
> > import cairocffi as cairo
> > ```
> > And existing code should still work.)

In which file do I add this line to?

**Comment by pkgw** [comment]
@Tarang74 It is very unlikely that you need to use the code snippet that you quoted. The recommended way to gain use Cairo in Python is to install the `pycairo` package. If that doesn't work, it is a bug that should be reported in [the pycairo feedstock](https://github.com/conda-forge/pycairo-feedstock/issues/).
