### ISSUE TITLE
freetype support in Windows build

### ISSUE THREAD

**Issue by anntzer** [conda-forge/cairo-feedstock#26]
It would be appreciated if the Windows build included freetype support.
A specific use case would be https://github.com/anntzer/mplcairo, which (on Linux, so far) renders text using cairo's freetype backend.
FWIW, https://github.com/preshing/cairo-windows/blob/master/build-cairo-windows.sh appears to be a (non-conda) recipe to build a cairo dll with freetype support.

**Comment by jakirkham** [comment]
Would you like to do a PR?

**Comment by anntzer** [comment]
Not right now for sure (hence the "it would be appreciated")...  just seeing if anyone is knowledgeable with this.

**Comment by oschwartz10612** [comment]
Hi, I am trying to organize [poppler-feedstock](https://github.com/conda-forge/poppler-feedstock) to build `pdftocairo` as per [this issue](https://github.com/conda-forge/poppler-feedstock/issues/66).

I am a bit new to the `conda` and `conda-forge` scene, so forgive me if I am miss-informed. It appears that `freetype` is being built for Windows. Is it just a matter of including `freetype` in the Windows pipeline and adding it to `CAIRO_LIBS`?

I am happy to do a PR if this is correct.

Thanks.

**Comment by pkgw** [comment]
@oschwartz10612 It might be that simple. Often there are surprising build issues when trying to integrate new dependencies to a library, especially on Windows. You can't really know until you try, though, so I encourage you to make an attempt and see if it works!

**Comment by oschwartz10612** [comment]
This issue can be closed.
