### ISSUE TITLE
Package snapshot releases?

### ISSUE THREAD

**Issue by pkgw** [conda-forge/cairo-feedstock#30]
We currently package the "stable" 1.14.x series of Cairo releases. But there is also the 1.15.x "[snapshot](https://cairographics.org/snapshots/)" series, which may not be "stable" but is at least formalized enough that there are numbered releases. The latest releases of the `librsvg` package rely on these snapshots, so we can't package them until something in the 1.15.x series or beyond gets packaged.

Anyway, the question is whether we should only package stable releases or start tracking the snapshots. I tend to think that we should stick with the stable series, but I wanted to bring the matter up for discussion.

**Comment by jakirkham** [comment]
We can add them to the `dev` label. Though we haven't really formalized it well. ( https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/3 ) There is a separate question about how we package things that depend on `dev` labels. Not sure what the answer is offhand.

**Comment by pkgw** [comment]
OK @conda-forge/cairo , there are several packages of interest to me that are blocking on the 1.15.x series of Cairo, so I would like to start packaging that series under a `dev` branch. Any concerns, etc?

**Comment by jakirkham** [comment]
Probably want to change the label they get uploaded to as well. As an example, please look at [this commit]( https://github.com/conda-forge/matplotlib-feedstock/commit/efd97afa3d80fc00584765d65a40a314d5beb669 ).

**Comment by pkgw** [comment]
Thanks for the pointer. The way to make that happen is to manually edit the various CI files?

**Comment by jakirkham** [comment]
Yeah that commit is less insightful than I would have hoped. Should only need to edit `conda-forge.yml`. Re-rendering will add it to the other CI files.

**Comment by pkgw** [comment]
I have [a branch](https://github.com/pkgw/cairo-feedstock/commits/dev) that implements the desired changes, I think, and passes CI. Should I just push it to the feedstock repo?

**Comment by pkgw** [comment]
Pulled the trigger.

**Comment by pkgw** [comment]
Errr, it looks like conda-smithy is no longer handling the `channels: targets:` construction. The files generated in `.ci_support` still specify `conda-forge main` as the target after rerendering and, based on my reading of the current conda-smithy source, I have trouble seeing how the information in `conda-forge.yaml` would make it into those files. @scopatz?

And @conda-forge/core can someone please manually relabel the 1.15 Cairo packages on anaconda.org to the "dev" label? Thanks.

**Comment by pkgw** [comment]
Ah, [conda-smithy #886](https://github.com/conda-forge/conda-smithy/issues/886).

**Comment by ocefpaf** [comment]
> And @conda-forge/core can someone please manually relabel the 1.15 Cairo packages on anaconda.org to the "dev" label? Thanks.

Done.

**Comment by pkgw** [comment]
Thanks @ocefpaf.
